# Generated by Django 4.1.3 on 2023-10-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_img_imgname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='submit/')),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='imge',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
